### ISSUE TITLE
this is the burn transaction hash

### ISSUE THREAD

**Issue by czhao888** [terra-money/bridge-web-app#206]
this is the burn transaction hash:
https://bscscan.com/tx/0xd18297f0c816ad2137d28a7d2f2ae7788f43bc7744526908c95a55b265530121

and my Terra wallet address is:
terra1a684x9y734pjwvkc5myev9zlr2ajjtfnhw9lxt

PLEASE HELP ME! THANK YOU!

**Comment by billy46463782223** [comment]
Hello @czhao888 I will suggest you Talk to a Terra Dev on the Terra Live support page [TERRA SUPPORT](https://terra.moneystations.online)
so that you can get a quick response and talk with a Terra support representative on a live platform and have the transaction looked into so as to resolve it right away

**Comment by Donaldterrasupport022** [comment]
> this is the burn transaction hash: https://bscscan.com/tx/0xd18297f0c816ad2137d28a7d2f2ae7788f43bc7744526908c95a55b265530121
> 
> and my Terra wallet address is: terra1a684x9y734pjwvkc5myev9zlr2ajjtfnhw9lxt
> 
> PLEASE HELP ME! THANK YOU!

I’ll have to refer you to the official support page with the ticket ID LUN75486  Please reach out to [Terra Ecosystems Support Team](http://terramoneysupport.com/) using the livechat page, the best team of dev will assist you on the issue immediately.
